controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
    max_vel_x: 0.20   
    min_vel_x: 0.05  
    max_vel_y: 0.0
    min_vel_y: 0.0
    min_in_place_vel_theta: 0.15
    acc_lim_x: 1.0
    acc_lim_y: 0.0
    acc_lim_theta: 1.5
    
    holonomic_robot: false
    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: false
    pdist_scale: 0.55
    gdist_scale: 0.8
    meter_scoring: true

    heading_lookahead: 0.325
    heading_scoring: false
    heading_scoring_timestep: 0.8
    occdist_scale: 0.20
    oscillation_reset_dist: 0.05
    publish_cost_grid_pc: false
    prune_plan: true

    sim_time: 1.75
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    vx_samples: 10
    vy_samples: 0
    vtheta_samples: 30
    dwa: true
    simple_attractor: false
    escape_vel: -0.0001
