local_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 15.0
   publish_frequency: 10.0
   static_map: true
   rolling_window: false
   width: 5.0
   height: 5.0
   resolution: 0.01
   transform_tolerance: 1.0

   scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update: 1}
