TrajectoryPlannerROS:
    max_vel_x: 0.25
    min_vel_x: 0.05  
    min_in_place_vel_theta: 0.15
    acc_lim_x: 0.1
    acc_lim_y: 0.2
    acc_lim_theta: 0.6
    
    holonomic_robot: false
    yaw_goal_tolerance: 2.0
    xy_goal_tolerance: 0.3
    meter_scoring: true

    sim_time: 1.75
 
    occdist_scale: 0.20

    escape_vel: -0.0000001

    recovery_behavior_enabled: false
    clearing_rotation_allowed: false
